#!/usr/bin/env python3
#exonware/xwsyntax/tests/2.integration/runner.py
"""
Integration test runner for xwsyntax.
Company: eXonware.com
Author: eXonware Backend Team
Email: connect@exonware.com
Version: 0.0.1
"""

import sys
import pytest
from pathlib import Path
from datetime import datetime
# ⚠️ CRITICAL: Configure UTF-8 encoding for Windows console using xwsystem utility
from exonware.xwsystem.console.cli import ensure_utf8_console
ensure_utf8_console()


def main():
    """Integration test runner."""
    src_path = Path(__file__).parent.parent.parent / "src"
    sys.path.insert(0, str(src_path))
    print("🔗 Integration Tests - Cross-Module Scenarios")
    exit_code = pytest.main([
        "-v",
        "--tb=short",
        str(Path(__file__).parent),
        "-m", "xwsyntax_integration"
    ])
    status = "✅ Integration tests PASSED" if exit_code == 0 else "❌ Integration tests FAILED"
    print(f"\n{status}")
    output_file = Path(__file__).parent / "runner_out.md"
    markdown_content = f"""# Integration Test Results
**Layer:** 2.integration  
**Generated:** {datetime.now().strftime("%d-%b-%Y %H:%M:%S")}  
**Status:** {'PASSED' if exit_code == 0 else 'FAILED'}
---
**Exit Code:** {exit_code}
---
*Generated by eXonware test runner*
"""
    output_file.write_text(markdown_content, encoding='utf-8')
    sys.exit(exit_code)
if __name__ == "__main__":
    main()
