#!/usr/bin/env python3
"""
#exonware/xwapi/src/exonware/xwapi/facade.py
Facade for turning entities and *exposable actions* into a runnable HTTP app (engine-agnostic).

*Build once, publish anywhere*: register ``XWAction``-decorated callables and optional entity
classes; pick ``engine="fastapi"`` (default, OpenAPI/async) or ``engine="flask"`` at
``create_app`` time. OpenAPI merges action specs with generated entity CRUD paths.

Company: eXonware.com
Author: eXonware Backend Team
Email: connect@exonware.com
Version: 0.9.0.12
"""

from typing import Any, Optional
import asyncio
import sys
import threading
from exonware.xwapi.base import AAPIGenerator
from exonware.xwapi.config import XWAPIConfig
from exonware.xwapi.contracts import IEntityCrudStore
from exonware.xwapi.entity_store import InMemoryEntityStore, XWStorageEntityStore
from exonware.xwapi.errors import (
    OpenAPIGenerationError,
    FastAPICreationError,
    NotFoundError,
    ServerLifecycleError,
    StorageUnavailableError,
)
from exonware.xwapi.defs import OpenAPISpec
from exonware.xwapi.common.app import create_app
from exonware.xwsystem import get_logger

logger = get_logger(__name__)


class XWAPI(AAPIGenerator):
    """
    Main facade: *publish* entities and XWAction-defined operations over HTTP.

    Combines OpenAPI from registered actions with optional entity CRUD routes. Server side
    of the “build once, publish anywhere” story; pair with ``XWApiAgent`` on the client.
    """

    def __init__(
        self,
        entities: list[Any] = None,
        storage: Any | None = None,
        entity_store: IEntityCrudStore | None = None,
        auth: Any | None = None,
        actions: list[Any] | None = None,
        config: XWAPIConfig | None = None,
        **kwargs,
    ):
        """
        Initialize XWAPI instance.
        Args:
            entities: List of entity classes to convert to API endpoints
            storage: Optional xwstorage instance for persistence
            auth: Optional xwauth instance for authentication
            actions: Optional list of xwaction-decorated functions to register as endpoints
            config: Optional XWAPIConfig instance
            **kwargs: Additional configuration options
        """
        self.entities = entities or []
        self.storage = storage
        self.auth = auth
        self.actions = actions or []
        # Merge kwargs into config
        if config:
            self.config = config
            for key, value in kwargs.items():
                if hasattr(self.config, key):
                    setattr(self.config, key, value)
        else:
            self.config = XWAPIConfig(**kwargs)
        self._openapi_spec: OpenAPISpec | None = None
        self._app: Any | None = None  # Engine-agnostic app instance
        # In-memory entity store used by autogenerated CRUD routes.
        self._entity_records: dict[str, dict[str, dict[str, Any]]] = {}
        self._entity_store: IEntityCrudStore = self._resolve_entity_store(entity_store)
        self._uvicorn_server: Any | None = None
        self._server_thread: threading.Thread | None = None
        self._server_lock = threading.RLock()
        self._last_start_config: dict[str, Any] | None = None
        self._engine_name: str | None = None

    def _resolve_entity_store(self, explicit_store: IEntityCrudStore | None) -> IEntityCrudStore:
        """Resolve the CRUD entity store backend."""
        if explicit_store is not None:
            return explicit_store
        if self.storage is not None:
            return XWStorageEntityStore(self.storage)
        return InMemoryEntityStore(self._entity_records)

    @staticmethod
    def _ensure_windows_event_loop_policy() -> None:
        """Apply Windows-compatible asyncio policy before uvicorn startup."""
        if sys.platform != "win32":
            return
        if not hasattr(asyncio, "WindowsSelectorEventLoopPolicy"):
            return
        policy_cls = asyncio.WindowsSelectorEventLoopPolicy
        try:
            if not isinstance(asyncio.get_event_loop_policy(), policy_cls):
                asyncio.set_event_loop_policy(policy_cls())
        except Exception:
            asyncio.set_event_loop_policy(policy_cls())

    def _build_uvicorn_server(self, host: str, port: int, **kwargs: Any) -> Any:
        """Create and cache an uvicorn server instance for this app."""
        if self._app is None:
            raise ServerLifecycleError("App must be created before starting server")
        import uvicorn

        self._ensure_windows_event_loop_policy()
        uvicorn_kwargs = {
            "host": host,
            "port": port,
            "log_level": kwargs.pop("log_level", "info"),
        }
        if sys.platform == "win32":
            uvicorn_kwargs["loop"] = "asyncio"
        elif "loop" in kwargs:
            uvicorn_kwargs["loop"] = kwargs.pop("loop")
        uvicorn_kwargs.update(kwargs)

        config = uvicorn.Config(self._app, **uvicorn_kwargs)
        if sys.platform == "win32":
            config.loop = "asyncio"
        server = uvicorn.Server(config)
        self._uvicorn_server = server
        return server

    @staticmethod
    def _entity_names(entity_cls: Any) -> tuple[str, str]:
        """Return (singular, plural) resource names for an entity class."""
        singular = getattr(entity_cls, "__name__", "entity").strip() or "entity"
        singular = singular.lower()
        plural = singular if singular.endswith("s") else f"{singular}s"
        return singular, plural

    @staticmethod
    def _py_type_to_openapi(py_type: Any) -> dict[str, Any]:
        """Map common Python types to OpenAPI schema snippets."""
        if py_type is bool:
            return {"type": "boolean"}
        if py_type is int:
            return {"type": "integer"}
        if py_type is float:
            return {"type": "number"}
        if py_type in (dict,):
            return {"type": "object"}
        if py_type in (list, tuple, set):
            return {"type": "array", "items": {"type": "object"}}
        return {"type": "string"}

    def _build_entity_schema(self, entity_cls: Any) -> dict[str, Any]:
        """Build an OpenAPI schema for an entity from type annotations."""
        annotations = getattr(entity_cls, "__annotations__", {}) or {}
        properties: dict[str, Any] = {"id": {"type": "string"}}
        required: list[str] = []
        for field_name, field_type in annotations.items():
            properties[field_name] = self._py_type_to_openapi(field_type)
            required.append(field_name)
        return {
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": True,
        }

    def _inject_entity_openapi(self, spec: OpenAPISpec) -> None:
        """Inject autogenerated CRUD paths/schemas for configured entities."""
        for entity_cls in self.entities:
            singular, plural = self._entity_names(entity_cls)
            schema_name = getattr(entity_cls, "__name__", "Entity")
            spec["components"]["schemas"][schema_name] = self._build_entity_schema(entity_cls)
            list_path = f"/{plural}"
            item_path = f"/{plural}/{{entity_id}}"
            spec["paths"].setdefault(list_path, {})
            spec["paths"][list_path]["get"] = {
                "summary": f"List {plural}",
                "tags": [plural],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {"type": "array", "items": {"$ref": f"#/components/schemas/{schema_name}"}}
                            }
                        },
                    }
                },
            }
            spec["paths"][list_path]["post"] = {
                "summary": f"Create {singular}",
                "tags": [plural],
                "requestBody": {
                    "required": True,
                    "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
                },
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
                    }
                },
            }
            spec["paths"].setdefault(item_path, {})
            spec["paths"][item_path]["get"] = {
                "summary": f"Get {singular}",
                "tags": [plural],
                "parameters": [{"name": "entity_id", "in": "path", "required": True, "schema": {"type": "string"}}],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
                    },
                    "404": {"description": "Not Found"},
                },
            }
            spec["paths"][item_path]["put"] = {
                "summary": f"Update {singular}",
                "tags": [plural],
                "parameters": [{"name": "entity_id", "in": "path", "required": True, "schema": {"type": "string"}}],
                "requestBody": {
                    "required": True,
                    "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
                },
                "responses": {
                    "200": {
                        "description": "Updated",
                        "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
                    },
                    "404": {"description": "Not Found"},
                },
            }
            spec["paths"][item_path]["delete"] = {
                "summary": f"Delete {singular}",
                "tags": [plural],
                "parameters": [{"name": "entity_id", "in": "path", "required": True, "schema": {"type": "string"}}],
                "responses": {"200": {"description": "Deleted"}, "404": {"description": "Not Found"}},
            }

    @staticmethod
    def _route_exists(app: Any, path: str, method: str) -> bool:
        """Check if a route path+method already exists on a framework app."""
        for route in getattr(app, "routes", []):
            route_path = getattr(route, "path", None)
            route_methods = getattr(route, "methods", None) or set()
            if route_path == path and method.upper() in route_methods:
                return True
        return False

    def _register_entity_routes_fastapi(self) -> None:
        """Register autogenerated CRUD routes for entities on a FastAPI app."""
        if self._app is None:
            return
        for entity_cls in self.entities:
            singular, plural = self._entity_names(entity_cls)
            list_path = f"/{plural}"
            item_path = f"/{plural}/{{entity_id}}"
            def make_list(collection: str) -> Any:
                async def list_entities() -> list[dict[str, Any]]:
                    try:
                        return await self._entity_store.list_items(collection)
                    except Exception as exc:
                        logger.exception("Failed listing entities", extra={"collection": collection})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while listing entities",
                            details={"collection": collection},
                        ) from exc
                return list_entities

            def make_create(collection: str) -> Any:
                async def create_entity(payload: dict[str, Any]) -> dict[str, Any]:
                    try:
                        existing = await self._entity_store.list_items(collection)
                        entity_id = str(payload.get("id") or payload.get("_id") or (len(existing) + 1))
                        entity = dict(payload)
                        entity["id"] = entity_id
                        await self._entity_store.put_item(collection, entity_id, entity)
                        return entity
                    except Exception as exc:
                        logger.exception("Failed creating entity", extra={"collection": collection})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while creating entity",
                            details={"collection": collection},
                        ) from exc
                return create_entity

            def make_get(collection: str, singular_ref: str) -> Any:
                async def get_entity(entity_id: str) -> dict[str, Any]:
                    try:
                        entity = await self._entity_store.get_item(collection, entity_id)
                    except Exception as exc:
                        logger.exception("Failed loading entity", extra={"collection": collection, "entity_id": entity_id})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while reading entity",
                            details={"collection": collection, "entity_id": entity_id},
                        ) from exc
                    if entity is None:
                        raise NotFoundError(
                            message=f"{singular_ref} not found",
                            details={"collection": collection, "entity_id": entity_id},
                        )
                    return entity
                return get_entity

            def make_update(collection: str, singular_ref: str) -> Any:
                async def update_entity(entity_id: str, payload: dict[str, Any]) -> dict[str, Any]:
                    try:
                        existing = await self._entity_store.get_item(collection, entity_id)
                    except Exception as exc:
                        logger.exception("Failed loading entity for update", extra={"collection": collection, "entity_id": entity_id})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while updating entity",
                            details={"collection": collection, "entity_id": entity_id},
                        ) from exc
                    if existing is None:
                        raise NotFoundError(
                            message=f"{singular_ref} not found",
                            details={"collection": collection, "entity_id": entity_id},
                        )
                    entity = dict(payload)
                    entity["id"] = entity_id
                    try:
                        await self._entity_store.put_item(collection, entity_id, entity)
                    except Exception as exc:
                        logger.exception("Failed writing updated entity", extra={"collection": collection, "entity_id": entity_id})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while updating entity",
                            details={"collection": collection, "entity_id": entity_id},
                        ) from exc
                    return entity
                return update_entity

            def make_delete(collection: str, singular_ref: str) -> Any:
                async def delete_entity(entity_id: str) -> dict[str, Any]:
                    try:
                        deleted = await self._entity_store.delete_item(collection, entity_id)
                    except Exception as exc:
                        logger.exception("Failed deleting entity", extra={"collection": collection, "entity_id": entity_id})
                        raise StorageUnavailableError(
                            message="Entity storage unavailable while deleting entity",
                            details={"collection": collection, "entity_id": entity_id},
                        ) from exc
                    if not deleted:
                        raise NotFoundError(
                            message=f"{singular_ref} not found",
                            details={"collection": collection, "entity_id": entity_id},
                        )
                    return {"ok": True, "id": entity_id}
                return delete_entity

            list_entities = make_list(plural)
            create_entity = make_create(plural)
            get_entity = make_get(plural, singular)
            update_entity = make_update(plural, singular)
            delete_entity = make_delete(plural, singular)

            if not self._route_exists(self._app, list_path, "GET"):
                self._app.add_api_route(list_path, list_entities, methods=["GET"], tags=[plural], summary=f"List {plural}")
            if not self._route_exists(self._app, list_path, "POST"):
                self._app.add_api_route(list_path, create_entity, methods=["POST"], tags=[plural], summary=f"Create {singular}")
            if not self._route_exists(self._app, item_path, "GET"):
                self._app.add_api_route(item_path, get_entity, methods=["GET"], tags=[plural], summary=f"Get {singular}")
            if not self._route_exists(self._app, item_path, "PUT"):
                self._app.add_api_route(item_path, update_entity, methods=["PUT"], tags=[plural], summary=f"Update {singular}")
            if not self._route_exists(self._app, item_path, "DELETE"):
                self._app.add_api_route(item_path, delete_entity, methods=["DELETE"], tags=[plural], summary=f"Delete {singular}")

    async def generate_openapi(self) -> OpenAPISpec:
        """
        Generate OpenAPI specification from entities and actions.
        Uses XWAction's OpenAPI generation capabilities.
        Returns:
            OpenAPI 3.1 specification dictionary
        Raises:
            OpenAPIGenerationError: If generation fails
        """
        try:
            # Start with base OpenAPI spec
            spec = {
                "openapi": "3.1.0",
                "info": {
                    "title": self.config.title,
                    "version": self.config.version,
                    "description": self.config.description or "",
                },
                "paths": {},
                "components": {
                    "schemas": {},
                    "securitySchemes": self.config.security_schemes or {},
                },
            }
            # Generate OpenAPI from XWAction actions
            for action in self.actions:
                if hasattr(action, 'xwaction'):
                    action_spec = action.xwaction.to_openapi()
                    # Merge action OpenAPI into main spec
                    if "paths" in action_spec:
                        spec["paths"].update(action_spec["paths"])
                    if "components" in action_spec:
                        if "schemas" in action_spec["components"]:
                            spec["components"]["schemas"].update(action_spec["components"]["schemas"])
            # Generate OpenAPI CRUD paths/schemas from provided entities.
            self._inject_entity_openapi(spec)
            self._openapi_spec = spec
            return self._openapi_spec
        except Exception as e:
            raise OpenAPIGenerationError(f"Failed to generate OpenAPI spec: {e}") from e

    def create_app(self, engine: str = "fastapi") -> Any:  # Engine-agnostic return type
        """
        Create application using xwapi.create_app() (engine-agnostic).
        Registers all actions using XWAction engine system.
        Args:
            engine: Engine name (default: "fastapi")
        Returns:
            Application instance (engine-specific)
        Raises:
            FastAPICreationError: If creation fails
        """
        try:
            if not self._openapi_spec:
                # Generate OpenAPI spec if not already generated
                self._openapi_spec = asyncio.run(self.generate_openapi())
            # Create app using xwapi factory (engine-agnostic)
            self._app = create_app(
                config=self.config,
                title=self.config.title,
                version=self.config.version,
                description=self.config.description,
                engine=engine,
            )
            self._engine_name = (engine or "").strip().lower() or None
            # Register all actions using XWAction engines directly
            # Prefer caller-selected engine; fall back to app-type detection only if needed.
            engine_name = self._engine_name
            if not engine_name:
                app_type_name = type(self._app).__module__ + "." + type(self._app).__name__
                if "fastapi" in app_type_name.lower():
                    engine_name = "fastapi"
                elif "flask" in app_type_name.lower():
                    engine_name = "flask"
            if engine_name:
                # Get XWAction engine for this framework
                try:
                    from exonware.xwaction.engines import action_engine_registry
                    action_engine = action_engine_registry.get_engine(engine_name)
                    if action_engine:
                        # Setup engine with app
                        action_engine.setup({"app": self._app})
                        # Register all actions
                        for action in self.actions:
                            if hasattr(action, 'xwaction'):
                                xwaction = action.xwaction
                                # Get path from action metadata
                                path = getattr(xwaction, 'operationId', None) or action.__name__
                                path = f"/{path}"
                                # Determine HTTP method from action profile
                                method = "POST"  # Default
                                if hasattr(xwaction, 'profile'):
                                    profile = xwaction.profile
                                    if hasattr(profile, 'value'):
                                        if profile.value == "query":
                                            method = "GET"
                                        elif profile.value == "command":
                                            method = "POST"
                                # Register using XWAction engine directly
                                action_engine.register_action(xwaction, self._app, path, method)
                except ImportError:
                    # XWAction not available, skip action registration
                    pass
                # Register entity-based CRUD routes for FastAPI runtime app.
                if engine_name == "fastapi":
                    self._register_entity_routes_fastapi()
            return self._app
        except Exception as e:
            raise FastAPICreationError(f"Failed to create app: {e}") from e

    def start(self, host: str = "0.0.0.0", port: int = 8000, blocking: bool = True, **kwargs) -> None:
        """
        Start the server (convenience method).
        Args:
            host: Host to bind to
            port: Port to bind to
            **kwargs: Additional server arguments
        """
        with self._server_lock:
            if self._uvicorn_server is not None:
                raise ServerLifecycleError("Server is already running for this XWAPI instance")
            if not self._app:
                self.create_app()
            logger.info(
                "Starting XWAPI server",
                extra={"host": host, "port": port, "blocking": blocking},
            )
            self._last_start_config = {
                "host": host,
                "port": port,
                "blocking": blocking,
                "kwargs": dict(kwargs),
            }
            server = self._build_uvicorn_server(host=host, port=port, **kwargs)
            if blocking:
                try:
                    server.run()
                finally:
                    self._uvicorn_server = None
                return

            def _run_server() -> None:
                try:
                    server.run()
                finally:
                    with self._server_lock:
                        self._uvicorn_server = None
                        self._server_thread = None

            thread = threading.Thread(target=_run_server, name="xwapi-uvicorn", daemon=True)
            self._server_thread = thread
            thread.start()

    def stop(self) -> None:
        """Stop the server."""
        with self._server_lock:
            server = self._uvicorn_server
            if server is None:
                logger.debug("XWAPI stop requested but server is not running")
                return
            logger.info("Stopping XWAPI server")
            server.should_exit = True
            thread = self._server_thread
        if thread is not None and thread.is_alive():
            thread.join(timeout=10.0)
            if thread.is_alive():
                raise ServerLifecycleError("Timed out while waiting for server thread to stop")

    def restart(self) -> None:
        """Restart the server."""
        if not self._last_start_config:
            raise ServerLifecycleError("Cannot restart before server has been started at least once")
        logger.info("Restarting XWAPI server")
        start_config = dict(self._last_start_config)
        self.stop()
        self.start(
            host=start_config["host"],
            port=start_config["port"],
            blocking=start_config["blocking"],
            **start_config["kwargs"],
        )
