from __future__ import annotations

import asyncio

import pytest

from exonware.xwapi import XWAPI
from exonware.xwentity import XWEntity


class User(XWEntity):
    name: str
    age: int


@pytest.mark.xwapi_unit
def test_generate_openapi_includes_entity_crud_paths() -> None:
    """XWAPI should auto-generate CRUD OpenAPI paths for configured entities."""
    api = XWAPI(entities=[User], title="Entity API", version="1.0.0")
    spec = asyncio.run(api.generate_openapi())
    paths = spec.get("paths", {})
    components = spec.get("components", {}).get("schemas", {})

    assert "/users" in paths
    assert "/users/{entity_id}" in paths
    assert "get" in paths["/users"]
    assert "post" in paths["/users"]
    assert "get" in paths["/users/{entity_id}"]
    assert "put" in paths["/users/{entity_id}"]
    assert "delete" in paths["/users/{entity_id}"]
    assert "User" in components
    assert "name" in components["User"]["properties"]
    assert "age" in components["User"]["properties"]


@pytest.mark.xwapi_unit
def test_create_app_registers_entity_crud_routes() -> None:
    """FastAPI app should include autogenerated CRUD routes for entities."""
    api = XWAPI(entities=[User], title="Entity API", version="1.0.0")
    app = api.create_app(engine="fastapi")

    route_paths = {getattr(route, "path", "") for route in app.routes}
    assert "/users" in route_paths
    assert "/users/{entity_id}" in route_paths


class _FakeEntityStore:
    def __init__(self):
        self.rows: dict[str, dict[str, dict[str, object]]] = {}

    async def list_items(self, collection: str) -> list[dict[str, object]]:
        return list(self.rows.setdefault(collection, {}).values())

    async def get_item(self, collection: str, entity_id: str) -> dict[str, object] | None:
        return self.rows.setdefault(collection, {}).get(entity_id)

    async def put_item(self, collection: str, entity_id: str, item: dict[str, object]) -> None:
        self.rows.setdefault(collection, {})[entity_id] = dict(item)

    async def delete_item(self, collection: str, entity_id: str) -> bool:
        if entity_id not in self.rows.setdefault(collection, {}):
            return False
        self.rows[collection].pop(entity_id)
        return True


@pytest.mark.xwapi_unit
def test_create_app_uses_custom_entity_store() -> None:
    """Custom entity store should be used for CRUD operations."""
    from fastapi.testclient import TestClient

    store = _FakeEntityStore()
    api = XWAPI(entities=[User], entity_store=store, title="Entity API", version="1.0.0")
    client = TestClient(api.create_app(engine="fastapi"))

    create_resp = client.post("/users", json={"id": "u1", "name": "Alice", "age": 30})
    assert create_resp.status_code == 200
    assert create_resp.json()["id"] == "u1"
    assert "u1" in store.rows.get("users", {})


class _FailingEntityStore:
    async def list_items(self, collection: str) -> list[dict[str, object]]:
        raise RuntimeError("storage down")

    async def get_item(self, collection: str, entity_id: str) -> dict[str, object] | None:
        raise RuntimeError("storage down")

    async def put_item(self, collection: str, entity_id: str, item: dict[str, object]) -> None:
        raise RuntimeError("storage down")

    async def delete_item(self, collection: str, entity_id: str) -> bool:
        raise RuntimeError("storage down")


@pytest.mark.xwapi_unit
def test_entity_store_failure_returns_service_unavailable() -> None:
    """Store backend failures should map to a typed 503 response."""
    from fastapi.testclient import TestClient

    api = XWAPI(entities=[User], entity_store=_FailingEntityStore(), title="Entity API", version="1.0.0")
    client = TestClient(api.create_app(engine="fastapi"))
    response = client.get("/users")
    body = response.json()
    assert response.status_code == 503
    assert body["code"] == "StorageUnavailableError"
    assert "trace_id" in body
