// wasm.monarch.ts
// Auto-generated Monaco language definition
export const wasmLanguage = {
  "defaultToken": "",
  "tokenPostfix": ".wasm",
  "keywords": [
    "binary",
    "block",
    "br",
    "call",
    "data",
    "drop",
    "elem",
    "else",
    "end",
    "export",
    "externref",
    "func",
    "funcref",
    "global",
    "if",
    "import",
    "local",
    "loop",
    "memory",
    "module",
    "mut",
    "nop",
    "offset",
    "param",
    "quote",
    "result",
    "return",
    "select",
    "start",
    "table",
    "then",
    "type",
    "unreachable"
  ],
  "operators": [
    "(",
    ")",
    ".",
    "=",
    "[^",
    "\\\\]*)*",
    "br_if",
    "br_table",
    "call_indirect",
    "f32",
    "f32.add",
    "f32.const",
    "f32.load",
    "f32.store",
    "f32.sub",
    "f64",
    "f64.add",
    "f64.const",
    "f64.load",
    "f64.store",
    "f64.sub",
    "i32",
    "i32.add",
    "i32.and",
    "i32.const",
    "i32.div_s",
    "i32.div_u",
    "i32.eq",
    "i32.eqz",
    "i32.ge_s",
    "i32.ge_u",
    "i32.gt_s",
    "i32.gt_u",
    "i32.le_s",
    "i32.le_u",
    "i32.load",
    "i32.lt_s",
    "i32.lt_u",
    "i32.mul",
    "i32.ne",
    "i32.or",
    "i32.rem_s",
    "i32.rem_u",
    "i32.shl",
    "i32.shr_s",
    "i32.shr_u",
    "i32.store",
    "i32.sub",
    "i32.xor",
    "i64",
    "i64.add",
    "i64.const",
    "i64.load",
    "i64.mul",
    "i64.store",
    "i64.sub",
    "v128"
  ],
  "symbols": "i32\\.or|i64\\.load|i64\\.mul|i64\\.store|i32\\.div_s|f32\\.add|i32\\.lt_u|i32\\.div_u|f32\\.sub|f64\\.sub|i32\\.ne|i64\\.add|i32|f64|i64\\.const|i64\\.sub|i32\\.const|i32\\.shr_s|\\[\\^|i32\\.eqz|i32\\.le_u|i32\\.ge_s|i32\\.ge_u|i32\\.mul|f64\\.store|\\(|\\\\\\\\\\]\\*\\)\\*|i32\\.le_s|f32\\.load|i32\\.load|br_if|i32\\.gt_s|i64|f64\\.const|i32\\.sub|f64\\.add|br_table|i32\\.eq|f64\\.load|i32\\.gt_u|i32\\.rem_s|=|i32\\.and|i32\\.shr_u|i32\\.lt_s|call_indirect|i32\\.rem_u|i32\\.store|i32\\.shl|f32\\.const|i32\\.xor|\\)|\\.|f32\\.store|f32|i32\\.add|v128",
  "brackets": [
    {
      "open": "(",
      "close": ")",
      "token": "delimiter.parenthesis"
    }
  ],
  "tokenizer": {
    "root": [
      {
        "include": "@whitespace"
      },
      [
        "/\\d+(\\.\\d+)?([eE][+-]?\\d+)?/",
        "number"
      ],
      [
        "/\"([^\"\\\\]|\\\\.)*\"/",
        "string"
      ],
      [
        "/'([^'\\\\]|\\\\.)*'/",
        "string"
      ],
      [
        "/[a-zA-Z_][\\w]*/",
        {
          "cases": {
            "@keywords": "keyword",
            "@default": "identifier"
          }
        }
      ],
      [
        "/call_indirect/",
        "operator"
      ],
      [
        "/i64\\.store/",
        "operator"
      ],
      [
        "/i32\\.div_s/",
        "operator"
      ],
      [
        "/i32\\.div_u/",
        "operator"
      ],
      [
        "/i64\\.const/",
        "operator"
      ],
      [
        "/i32\\.const/",
        "operator"
      ],
      [
        "/i32\\.shr_s/",
        "operator"
      ],
      [
        "/f64\\.store/",
        "operator"
      ],
      [
        "/f64\\.const/",
        "operator"
      ],
      [
        "/i32\\.rem_s/",
        "operator"
      ],
      [
        "/i32\\.shr_u/",
        "operator"
      ],
      [
        "/i32\\.rem_u/",
        "operator"
      ],
      [
        "/i32\\.store/",
        "operator"
      ],
      [
        "/f32\\.const/",
        "operator"
      ],
      [
        "/f32\\.store/",
        "operator"
      ],
      [
        "/i64\\.load/",
        "operator"
      ],
      [
        "/i32\\.lt_u/",
        "operator"
      ],
      [
        "/i32\\.le_u/",
        "operator"
      ],
      [
        "/i32\\.ge_s/",
        "operator"
      ],
      [
        "/i32\\.ge_u/",
        "operator"
      ],
      [
        "/i32\\.le_s/",
        "operator"
      ],
      [
        "/f32\\.load/",
        "operator"
      ],
      [
        "/i32\\.load/",
        "operator"
      ],
      [
        "/i32\\.gt_s/",
        "operator"
      ],
      [
        "/br_table/",
        "operator"
      ],
      [
        "/f64\\.load/",
        "operator"
      ],
      [
        "/i32\\.gt_u/",
        "operator"
      ],
      [
        "/i32\\.lt_s/",
        "operator"
      ],
      [
        "/i64\\.mul/",
        "operator"
      ],
      [
        "/f32\\.add/",
        "operator"
      ],
      [
        "/f32\\.sub/",
        "operator"
      ],
      [
        "/f64\\.sub/",
        "operator"
      ],
      [
        "/i64\\.add/",
        "operator"
      ],
      [
        "/i64\\.sub/",
        "operator"
      ],
      [
        "/i32\\.eqz/",
        "operator"
      ],
      [
        "/i32\\.mul/",
        "operator"
      ],
      [
        "/i32\\.sub/",
        "operator"
      ],
      [
        "/f64\\.add/",
        "operator"
      ],
      [
        "/i32\\.and/",
        "operator"
      ],
      [
        "/i32\\.shl/",
        "operator"
      ],
      [
        "/i32\\.xor/",
        "operator"
      ],
      [
        "/i32\\.add/",
        "operator"
      ],
      [
        "/i32\\.or/",
        "operator"
      ],
      [
        "/i32\\.ne/",
        "operator"
      ],
      [
        "/\\\\\\\\\\]\\*\\)\\*/",
        "operator"
      ],
      [
        "/i32\\.eq/",
        "operator"
      ],
      [
        "/br_if/",
        "operator"
      ],
      [
        "/v128/",
        "operator"
      ],
      [
        "/i32/",
        "operator"
      ],
      [
        "/f64/",
        "operator"
      ],
      [
        "/i64/",
        "operator"
      ],
      [
        "/f32/",
        "operator"
      ],
      [
        "/\\[\\^/",
        "operator"
      ],
      [
        "/\\(/",
        "operator"
      ],
      [
        "/=/",
        "operator"
      ],
      [
        "/\\)/",
        "operator"
      ],
      [
        "/\\./",
        "operator"
      ],
      [
        "/[()[\\]{}]/",
        "@brackets"
      ],
      [
        "/[;,.]/",
        "delimiter"
      ]
    ],
    "whitespace": [
      [
        "/[ \\t\\r\\n]+/",
        ""
      ],
      [
        "/--.*$/",
        "comment"
      ],
      [
        "/\\/\\/.*$/",
        "comment"
      ],
      [
        "/\\/\\*/",
        "comment",
        "@comment"
      ]
    ],
    "comment": [
      [
        "/[^/*]+/",
        "comment"
      ],
      [
        "/\\*\\//",
        "comment",
        "@pop"
      ],
      [
        "/[/*]/",
        "comment"
      ]
    ]
  }
};
export const wasmLanguageConfig = {
  "brackets": [
    [
      "(",
      ")"
    ]
  ],
  "autoClosingPairs": [
    {
      "open": "(",
      "close": ")"
    },
    {
      "open": "'",
      "close": "'"
    }
  ],
  "surroundingPairs": [
    {
      "open": "(",
      "close": ")"
    },
    {
      "open": "'",
      "close": "'"
    }
  ]
};
// Register with Monaco Editor
export function registerWasmLanguage(monaco: any) {
  monaco.languages.register({ id: 'wasm' });
  monaco.languages.setMonarchTokensProvider('wasm', wasmLanguage);
  monaco.languages.setLanguageConfiguration('wasm', wasmLanguageConfig);
}
