from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from exonware.xwapi import XWAPI
# Import from implementation module so tests do not depend on exonware.xwentity __init__
# ordering vs. lazy hooks when the full stack is assembled from editable installs.
from exonware.xwentity.entity import XWEntity


class User(XWEntity):
    name: str
    age: int


@pytest.mark.xwapi_integration
def test_entity_crud_flow_autogenerated_routes() -> None:
    """Autogenerated entity CRUD routes should support full basic lifecycle."""
    api = XWAPI(entities=[User], title="Entity CRUD API", version="1.0.0")
    app = api.create_app(engine="fastapi")
    client = TestClient(app)

    create_resp = client.post("/users", json={"name": "Alice", "age": 30})
    assert create_resp.status_code == 200
    created = create_resp.json()
    assert created["name"] == "Alice"
    assert created["age"] == 30
    assert "id" in created
    entity_id = created["id"]

    list_resp = client.get("/users")
    assert list_resp.status_code == 200
    items = list_resp.json()
    assert isinstance(items, list)
    assert len(items) == 1
    assert items[0]["id"] == entity_id

    get_resp = client.get(f"/users/{entity_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["name"] == "Alice"

    update_resp = client.put(f"/users/{entity_id}", json={"name": "Alice Updated", "age": 31})
    assert update_resp.status_code == 200
    updated = update_resp.json()
    assert updated["id"] == entity_id
    assert updated["name"] == "Alice Updated"
    assert updated["age"] == 31

    delete_resp = client.delete(f"/users/{entity_id}")
    assert delete_resp.status_code == 200
    assert delete_resp.json()["ok"] is True

    missing_resp = client.get(f"/users/{entity_id}")
    assert missing_resp.status_code == 404


@pytest.mark.xwapi_integration
def test_entity_crud_persists_with_xwstorage(tmp_path) -> None:
    """Entity CRUD should persist across app instances when xwstorage is provided."""
    xwstorage = pytest.importorskip("exonware.xwstorage")
    storage_path = tmp_path / "entity_store.json"
    storage = xwstorage.XWStorage(backend="local", format="json", address=str(storage_path))

    first_api = XWAPI(entities=[User], storage=storage, title="Entity CRUD API", version="1.0.0")
    first_client = TestClient(first_api.create_app(engine="fastapi"))

    create_resp = first_client.post("/users", json={"id": "user-1", "name": "Alice", "age": 30})
    assert create_resp.status_code == 200

    second_api = XWAPI(entities=[User], storage=storage, title="Entity CRUD API", version="1.0.0")
    second_client = TestClient(second_api.create_app(engine="fastapi"))
    list_resp = second_client.get("/users")

    assert list_resp.status_code == 200
    items = list_resp.json()
    assert len(items) == 1
    assert items[0]["id"] == "user-1"
