// Generated by tools/generate-component-index.ts - do not edit by hand
export const components = [
  {
    "name": "XWINumberInput",
    "path": "component/XWINumberInput",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWINumberInput.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWINumberInput\\testers\\TesterXWINumberInput.html",
        "relativePath": "component/XWINumberInput/testers/TesterXWINumberInput.html"
      }
    ]
  },
  {
    "name": "XWUIAccordion",
    "path": "component/XWUIAccordion",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAccordion.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAccordion\\testers\\TesterXWUIAccordion.html",
        "relativePath": "component/XWUIAccordion/testers/TesterXWUIAccordion.html"
      }
    ]
  },
  {
    "name": "XWUIActivityFilter",
    "path": "component/XWUIActivityFilter",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIActivityFilter.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIActivityFilter\\testers\\TesterXWUIActivityFilter.html",
        "relativePath": "component/XWUIActivityFilter/testers/TesterXWUIActivityFilter.html"
      }
    ]
  },
  {
    "name": "XWUIAffix",
    "path": "component/XWUIAffix",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAffix.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAffix\\testers\\TesterXWUIAffix.html",
        "relativePath": "component/XWUIAffix/testers/TesterXWUIAffix.html"
      }
    ]
  },
  {
    "name": "XWUIAlert",
    "path": "component/XWUIAlert",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAlert.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAlert\\testers\\TesterXWUIAlert.html",
        "relativePath": "component/XWUIAlert/testers/TesterXWUIAlert.html"
      }
    ]
  },
  {
    "name": "XWUIAnchor",
    "path": "component/XWUIAnchor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAnchor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAnchor\\testers\\TesterXWUIAnchor.html",
        "relativePath": "component/XWUIAnchor/testers/TesterXWUIAnchor.html"
      }
    ]
  },
  {
    "name": "XWUIAppBar",
    "path": "component/XWUIAppBar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAppBar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAppBar\\testers\\TesterXWUIAppBar.html",
        "relativePath": "component/XWUIAppBar/testers/TesterXWUIAppBar.html"
      }
    ]
  },
  {
    "name": "XWUIApprovalWorkflow",
    "path": "super/XWUIApprovalWorkflow",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIApprovalWorkflow.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIApprovalWorkflow\\testers\\TesterXWUIApprovalWorkflow.html",
        "relativePath": "super/XWUIApprovalWorkflow/testers/TesterXWUIApprovalWorkflow.html"
      }
    ]
  },
  {
    "name": "XWUIAppShell",
    "path": "power/XWUIAppShell",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAppShell.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIAppShell\\testers\\TesterXWUIAppShell.html",
        "relativePath": "power/XWUIAppShell/testers/TesterXWUIAppShell.html"
      }
    ]
  },
  {
    "name": "XWUIAspectRatio",
    "path": "component/XWUIAspectRatio",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAspectRatio.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAspectRatio\\testers\\TesterXWUIAspectRatio.html",
        "relativePath": "component/XWUIAspectRatio/testers/TesterXWUIAspectRatio.html"
      }
    ]
  },
  {
    "name": "XWUIAudioEditor",
    "path": "super/XWUIAudioEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAudioEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIAudioEditor\\testers\\TesterXWUIAudioEditor.html",
        "relativePath": "super/XWUIAudioEditor/testers/TesterXWUIAudioEditor.html"
      }
    ]
  },
  {
    "name": "XWUIAudioPlayer",
    "path": "super/XWUIAudioPlayer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAudioPlayer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIAudioPlayer\\testers\\TesterXWUIAudioPlayer.html",
        "relativePath": "super/XWUIAudioPlayer/testers/TesterXWUIAudioPlayer.html"
      }
    ]
  },
  {
    "name": "XWUIAudioRecorder",
    "path": "super/XWUIAudioRecorder",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAudioRecorder.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIAudioRecorder\\testers\\TesterXWUIAudioRecorder.html",
        "relativePath": "super/XWUIAudioRecorder/testers/TesterXWUIAudioRecorder.html"
      }
    ]
  },
  {
    "name": "XWUIAutocomplete",
    "path": "component/XWUIAutocomplete",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAutocomplete.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAutocomplete\\testers\\TesterXWUIAutocomplete.html",
        "relativePath": "component/XWUIAutocomplete/testers/TesterXWUIAutocomplete.html"
      }
    ]
  },
  {
    "name": "XWUIAvatar",
    "path": "component/XWUIAvatar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAvatar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAvatar\\testers\\TesterXWUIAvatar.html",
        "relativePath": "component/XWUIAvatar/testers/TesterXWUIAvatar.html"
      }
    ]
  },
  {
    "name": "XWUIAvatarGroup",
    "path": "component/XWUIAvatarGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIAvatarGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIAvatarGroup\\testers\\TesterXWUIAvatarGroup.html",
        "relativePath": "component/XWUIAvatarGroup/testers/TesterXWUIAvatarGroup.html"
      }
    ]
  },
  {
    "name": "XWUIBackdrop",
    "path": "component/XWUIBackdrop",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBackdrop.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBackdrop\\testers\\TesterXWUIBackdrop.html",
        "relativePath": "component/XWUIBackdrop/testers/TesterXWUIBackdrop.html"
      }
    ]
  },
  {
    "name": "XWUIBackToTop",
    "path": "component/XWUIBackToTop",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBackToTop.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBackToTop\\testers\\TesterXWUIBackToTop.html",
        "relativePath": "component/XWUIBackToTop/testers/TesterXWUIBackToTop.html"
      }
    ]
  },
  {
    "name": "XWUIBadge",
    "path": "component/XWUIBadge",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBadge.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBadge\\testers\\TesterXWUIBadge.html",
        "relativePath": "component/XWUIBadge/testers/TesterXWUIBadge.html"
      }
    ]
  },
  {
    "name": "XWUIBottomNavigation",
    "path": "component/XWUIBottomNavigation",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBottomNavigation.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBottomNavigation\\testers\\TesterXWUIBottomNavigation.html",
        "relativePath": "component/XWUIBottomNavigation/testers/TesterXWUIBottomNavigation.html"
      }
    ]
  },
  {
    "name": "XWUIBottomSheet",
    "path": "component/XWUIBottomSheet",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBottomSheet.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBottomSheet\\testers\\TesterXWUIBottomSheet.html",
        "relativePath": "component/XWUIBottomSheet/testers/TesterXWUIBottomSheet.html"
      }
    ]
  },
  {
    "name": "XWUIBox",
    "path": "component/XWUIBox",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBox.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBox\\testers\\TesterXWUIBox.html",
        "relativePath": "component/XWUIBox/testers/TesterXWUIBox.html"
      }
    ]
  },
  {
    "name": "XWUIBreadcrumbs",
    "path": "component/XWUIBreadcrumbs",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBreadcrumbs.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBreadcrumbs\\testers\\TesterXWUIBreadcrumbs.html",
        "relativePath": "component/XWUIBreadcrumbs/testers/TesterXWUIBreadcrumbs.html"
      }
    ]
  },
  {
    "name": "XWUIBrightness",
    "path": "component/XWUIBrightness",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBrightness.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBrightness\\testers\\TesterXWUIBrightness.html",
        "relativePath": "component/XWUIBrightness/testers/TesterXWUIBrightness.html"
      }
    ]
  },
  {
    "name": "XWUIBulkActionBar",
    "path": "component/XWUIBulkActionBar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIBulkActionBar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIBulkActionBar\\testers\\TesterXWUIBulkActionBar.html",
        "relativePath": "component/XWUIBulkActionBar/testers/TesterXWUIBulkActionBar.html"
      }
    ]
  },
  {
    "name": "XWUIButton",
    "path": "component/XWUIButton",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIButton.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIButton\\testers\\TesterXWUIButton.html",
        "relativePath": "component/XWUIButton/testers/TesterXWUIButton.html"
      },
      {
        "name": "Three-ways",
        "filename": "TesterXWUIButton.three-ways.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIButton\\testers\\TesterXWUIButton.three-ways.html",
        "relativePath": "component/XWUIButton/testers/TesterXWUIButton.three-ways.html"
      },
      {
        "name": "web-component",
        "filename": "TesterXWUIButton.web-component.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIButton\\testers\\TesterXWUIButton.web-component.html",
        "relativePath": "component/XWUIButton/testers/TesterXWUIButton.web-component.html"
      }
    ]
  },
  {
    "name": "XWUIButtonGroup",
    "path": "component/XWUIButtonGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIButtonGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIButtonGroup\\testers\\TesterXWUIButtonGroup.html",
        "relativePath": "component/XWUIButtonGroup/testers/TesterXWUIButtonGroup.html"
      }
    ]
  },
  {
    "name": "XWUICalendar",
    "path": "component/XWUICalendar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICalendar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICalendar\\testers\\TesterXWUICalendar.html",
        "relativePath": "component/XWUICalendar/testers/TesterXWUICalendar.html"
      }
    ]
  },
  {
    "name": "XWUICard",
    "path": "component/XWUICard",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICard.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICard\\testers\\TesterXWUICard.html",
        "relativePath": "component/XWUICard/testers/TesterXWUICard.html"
      }
    ]
  },
  {
    "name": "XWUICarousel",
    "path": "component/XWUICarousel",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICarousel.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICarousel\\testers\\TesterXWUICarousel.html",
        "relativePath": "component/XWUICarousel/testers/TesterXWUICarousel.html"
      }
    ]
  },
  {
    "name": "XWUICascader",
    "path": "component/XWUICascader",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICascader.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICascader\\testers\\TesterXWUICascader.html",
        "relativePath": "component/XWUICascader/testers/TesterXWUICascader.html"
      }
    ]
  },
  {
    "name": "XWUICenter",
    "path": "component/XWUICenter",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICenter.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICenter\\testers\\TesterXWUICenter.html",
        "relativePath": "component/XWUICenter/testers/TesterXWUICenter.html"
      }
    ]
  },
  {
    "name": "XWUIChangeDiffViewer",
    "path": "power/XWUIChangeDiffViewer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIChangeDiffViewer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIChangeDiffViewer\\testers\\TesterXWUIChangeDiffViewer.html",
        "relativePath": "power/XWUIChangeDiffViewer/testers/TesterXWUIChangeDiffViewer.html"
      }
    ]
  },
  {
    "name": "XWUIChannelList",
    "path": "component/XWUIChannelList",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIChannelList.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIChannelList\\testers\\TesterXWUIChannelList.html",
        "relativePath": "component/XWUIChannelList/testers/TesterXWUIChannelList.html"
      }
    ]
  },
  {
    "name": "XWUIChart",
    "path": "power/XWUIChart",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIChart.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIChart\\testers\\TesterXWUIChart.html",
        "relativePath": "power/XWUIChart/testers/TesterXWUIChart.html"
      }
    ]
  },
  {
    "name": "XWUICheckbox",
    "path": "component/XWUICheckbox",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICheckbox.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICheckbox\\testers\\TesterXWUICheckbox.html",
        "relativePath": "component/XWUICheckbox/testers/TesterXWUICheckbox.html"
      }
    ]
  },
  {
    "name": "XWUIChip",
    "path": "component/XWUIChip",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIChip.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIChip\\testers\\TesterXWUIChip.html",
        "relativePath": "component/XWUIChip/testers/TesterXWUIChip.html"
      }
    ]
  },
  {
    "name": "XWUICodeBlock",
    "path": "power/XWUICodeBlock",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICodeBlock.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUICodeBlock\\testers\\TesterXWUICodeBlock.html",
        "relativePath": "power/XWUICodeBlock/testers/TesterXWUICodeBlock.html"
      }
    ]
  },
  {
    "name": "XWUICollapse",
    "path": "component/XWUICollapse",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICollapse.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICollapse\\testers\\TesterXWUICollapse.html",
        "relativePath": "component/XWUICollapse/testers/TesterXWUICollapse.html"
      }
    ]
  },
  {
    "name": "XWUIColorPicker",
    "path": "component/XWUIColorPicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIColorPicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIColorPicker\\testers\\TesterXWUIColorPicker.html",
        "relativePath": "component/XWUIColorPicker/testers/TesterXWUIColorPicker.html"
      }
    ]
  },
  {
    "name": "XWUICommand",
    "path": "power/XWUICommand",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICommand.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUICommand\\testers\\TesterXWUICommand.html",
        "relativePath": "power/XWUICommand/testers/TesterXWUICommand.html"
      }
    ]
  },
  {
    "name": "XWUIComponent",
    "path": "component/XWUIComponent",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIComponent.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIComponent\\testers\\TesterXWUIComponent.html",
        "relativePath": "component/XWUIComponent/testers/TesterXWUIComponent.html"
      }
    ]
  },
  {
    "name": "XWUIComponentPropertyForm",
    "path": "power/XWUIComponentPropertyForm",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIComponentPropertyForm.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIComponentPropertyForm\\testers\\TesterXWUIComponentPropertyForm.html",
        "relativePath": "power/XWUIComponentPropertyForm/testers/TesterXWUIComponentPropertyForm.html"
      }
    ]
  },
  {
    "name": "XWUIConsole",
    "path": "power/XWUIConsole",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIConsole.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIConsole\\testers\\TesterXWUIConsole.html",
        "relativePath": "power/XWUIConsole/testers/TesterXWUIConsole.html"
      }
    ]
  },
  {
    "name": "XWUIContainer",
    "path": "component/XWUIContainer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIContainer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIContainer\\testers\\TesterXWUIContainer.html",
        "relativePath": "component/XWUIContainer/testers/TesterXWUIContainer.html"
      }
    ]
  },
  {
    "name": "XWUICopyButton",
    "path": "component/XWUICopyButton",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUICopyButton.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUICopyButton\\testers\\TesterXWUICopyButton.html",
        "relativePath": "component/XWUICopyButton/testers/TesterXWUICopyButton.html"
      }
    ]
  },
  {
    "name": "XWUIDataGrid",
    "path": "power/XWUIDataGrid",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDataGrid.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIDataGrid\\testers\\TesterXWUIDataGrid.html",
        "relativePath": "power/XWUIDataGrid/testers/TesterXWUIDataGrid.html"
      }
    ]
  },
  {
    "name": "XWUIDatePicker",
    "path": "component/XWUIDatePicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDatePicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIDatePicker\\testers\\TesterXWUIDatePicker.html",
        "relativePath": "component/XWUIDatePicker/testers/TesterXWUIDatePicker.html"
      }
    ]
  },
  {
    "name": "XWUIDateRangePicker",
    "path": "component/XWUIDateRangePicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDateRangePicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIDateRangePicker\\testers\\TesterXWUIDateRangePicker.html",
        "relativePath": "component/XWUIDateRangePicker/testers/TesterXWUIDateRangePicker.html"
      }
    ]
  },
  {
    "name": "XWUIDebugToolbar",
    "path": "power/XWUIDebugToolbar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDebugToolbar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIDebugToolbar\\testers\\TesterXWUIDebugToolbar.html",
        "relativePath": "power/XWUIDebugToolbar/testers/TesterXWUIDebugToolbar.html"
      }
    ]
  },
  {
    "name": "XWUIDependencyVisualizer",
    "path": "super/XWUIDependencyVisualizer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDependencyVisualizer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIDependencyVisualizer\\testers\\TesterXWUIDependencyVisualizer.html",
        "relativePath": "super/XWUIDependencyVisualizer/testers/TesterXWUIDependencyVisualizer.html"
      }
    ]
  },
  {
    "name": "XWUIDescriptionList",
    "path": "component/XWUIDescriptionList",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDescriptionList.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIDescriptionList\\testers\\TesterXWUIDescriptionList.html",
        "relativePath": "component/XWUIDescriptionList/testers/TesterXWUIDescriptionList.html"
      }
    ]
  },
  {
    "name": "XWUIDiagram",
    "path": "super/XWUIDiagram",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDiagram.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIDiagram\\testers\\TesterXWUIDiagram.html",
        "relativePath": "super/XWUIDiagram/testers/TesterXWUIDiagram.html"
      }
    ]
  },
  {
    "name": "XWUIDialog",
    "path": "component/XWUIDialog",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDialog.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIDialog\\testers\\TesterXWUIDialog.html",
        "relativePath": "component/XWUIDialog/testers/TesterXWUIDialog.html"
      }
    ]
  },
  {
    "name": "XWUIDiffEditor",
    "path": "power/XWUIDiffEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDiffEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIDiffEditor\\testers\\TesterXWUIDiffEditor.html",
        "relativePath": "power/XWUIDiffEditor/testers/TesterXWUIDiffEditor.html"
      }
    ]
  },
  {
    "name": "XWUIDurationPicker",
    "path": "component/XWUIDurationPicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDurationPicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIDurationPicker\\testers\\TesterXWUIDurationPicker.html",
        "relativePath": "component/XWUIDurationPicker/testers/TesterXWUIDurationPicker.html"
      }
    ]
  },
  {
    "name": "XWUIDynamicFieldRenderer",
    "path": "power/XWUIDynamicFieldRenderer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIDynamicFieldRenderer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIDynamicFieldRenderer\\testers\\TesterXWUIDynamicFieldRenderer.html",
        "relativePath": "power/XWUIDynamicFieldRenderer/testers/TesterXWUIDynamicFieldRenderer.html"
      }
    ]
  },
  {
    "name": "XWUIEmpty",
    "path": "component/XWUIEmpty",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIEmpty.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIEmpty\\testers\\TesterXWUIEmpty.html",
        "relativePath": "component/XWUIEmpty/testers/TesterXWUIEmpty.html"
      }
    ]
  },
  {
    "name": "XWUIField",
    "path": "component/XWUIField",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIField.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIField\\testers\\TesterXWUIField.html",
        "relativePath": "component/XWUIField/testers/TesterXWUIField.html"
      }
    ]
  },
  {
    "name": "XWUIFilePreview",
    "path": "component/XWUIFilePreview",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFilePreview.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIFilePreview\\testers\\TesterXWUIFilePreview.html",
        "relativePath": "component/XWUIFilePreview/testers/TesterXWUIFilePreview.html"
      }
    ]
  },
  {
    "name": "XWUIFilters",
    "path": "component/XWUIFilters",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFilters.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIFilters\\testers\\TesterXWUIFilters.html",
        "relativePath": "component/XWUIFilters/testers/TesterXWUIFilters.html"
      }
    ]
  },
  {
    "name": "XWUIFlex",
    "path": "component/XWUIFlex",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFlex.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIFlex\\testers\\TesterXWUIFlex.html",
        "relativePath": "component/XWUIFlex/testers/TesterXWUIFlex.html"
      }
    ]
  },
  {
    "name": "XWUIFocusTrap",
    "path": "component/XWUIFocusTrap",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFocusTrap.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIFocusTrap\\testers\\TesterXWUIFocusTrap.html",
        "relativePath": "component/XWUIFocusTrap/testers/TesterXWUIFocusTrap.html"
      }
    ]
  },
  {
    "name": "XWUIFollowIndicator",
    "path": "component/XWUIFollowIndicator",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFollowIndicator.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIFollowIndicator\\testers\\TesterXWUIFollowIndicator.html",
        "relativePath": "component/XWUIFollowIndicator/testers/TesterXWUIFollowIndicator.html"
      }
    ]
  },
  {
    "name": "XWUIForm",
    "path": "component/XWUIForm",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIForm.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIForm\\testers\\TesterXWUIForm.html",
        "relativePath": "component/XWUIForm/testers/TesterXWUIForm.html"
      }
    ]
  },
  {
    "name": "XWUIFormEditor",
    "path": "super/XWUIFormEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIFormEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIFormEditor\\testers\\TesterXWUIFormEditor.html",
        "relativePath": "super/XWUIFormEditor/testers/TesterXWUIFormEditor.html"
      }
    ]
  },
  {
    "name": "XWUIGalleryEditor",
    "path": "super/XWUIGalleryEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIGalleryEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIGalleryEditor\\testers\\TesterXWUIGalleryEditor.html",
        "relativePath": "super/XWUIGalleryEditor/testers/TesterXWUIGalleryEditor.html"
      }
    ]
  },
  {
    "name": "XWUIGalleryViewer",
    "path": "super/XWUIGalleryViewer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIGalleryViewer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIGalleryViewer\\testers\\TesterXWUIGalleryViewer.html",
        "relativePath": "super/XWUIGalleryViewer/testers/TesterXWUIGalleryViewer.html"
      }
    ]
  },
  {
    "name": "XWUIGanttChart",
    "path": "super/XWUIGanttChart",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIGanttChart.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIGanttChart\\testers\\TesterXWUIGanttChart.html",
        "relativePath": "super/XWUIGanttChart/testers/TesterXWUIGanttChart.html"
      }
    ]
  },
  {
    "name": "XWUIGrid",
    "path": "component/XWUIGrid",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIGrid.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIGrid\\testers\\TesterXWUIGrid.html",
        "relativePath": "component/XWUIGrid/testers/TesterXWUIGrid.html"
      }
    ]
  },
  {
    "name": "XWUIHidden",
    "path": "component/XWUIHidden",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIHidden.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIHidden\\testers\\TesterXWUIHidden.html",
        "relativePath": "component/XWUIHidden/testers/TesterXWUIHidden.html"
      }
    ]
  },
  {
    "name": "XWUIHoverCard",
    "path": "component/XWUIHoverCard",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIHoverCard.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIHoverCard\\testers\\TesterXWUIHoverCard.html",
        "relativePath": "component/XWUIHoverCard/testers/TesterXWUIHoverCard.html"
      }
    ]
  },
  {
    "name": "XWUIIcon",
    "path": "component/XWUIIcon",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIIcon.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIIcon\\testers\\TesterXWUIIcon.html",
        "relativePath": "component/XWUIIcon/testers/TesterXWUIIcon.html"
      }
    ]
  },
  {
    "name": "XWUIImage",
    "path": "component/XWUIImage",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIImage.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIImage\\testers\\TesterXWUIImage.html",
        "relativePath": "component/XWUIImage/testers/TesterXWUIImage.html"
      }
    ]
  },
  {
    "name": "XWUIInput",
    "path": "component/XWUIInput",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInput.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInput\\testers\\TesterXWUIInput.html",
        "relativePath": "component/XWUIInput/testers/TesterXWUIInput.html"
      }
    ]
  },
  {
    "name": "XWUIInputChat",
    "path": "component/XWUIInputChat",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputChat.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputChat\\testers\\TesterXWUIInputChat.html",
        "relativePath": "component/XWUIInputChat/testers/TesterXWUIInputChat.html"
      }
    ]
  },
  {
    "name": "XWUIInputColor",
    "path": "component/XWUIInputColor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputColor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputColor\\testers\\TesterXWUIInputColor.html",
        "relativePath": "component/XWUIInputColor/testers/TesterXWUIInputColor.html"
      }
    ]
  },
  {
    "name": "XWUIInputDate",
    "path": "component/XWUIInputDate",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputDate.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputDate\\testers\\TesterXWUIInputDate.html",
        "relativePath": "component/XWUIInputDate/testers/TesterXWUIInputDate.html"
      }
    ]
  },
  {
    "name": "XWUIInputDateRange",
    "path": "component/XWUIInputDateRange",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputDateRange.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputDateRange\\testers\\TesterXWUIInputDateRange.html",
        "relativePath": "component/XWUIInputDateRange/testers/TesterXWUIInputDateRange.html"
      }
    ]
  },
  {
    "name": "XWUIInputGroup",
    "path": "component/XWUIInputGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputGroup\\testers\\TesterXWUIInputGroup.html",
        "relativePath": "component/XWUIInputGroup/testers/TesterXWUIInputGroup.html"
      }
    ]
  },
  {
    "name": "XWUIInputJson",
    "path": "component/XWUIInputJson",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputJson.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputJson\\testers\\TesterXWUIInputJson.html",
        "relativePath": "component/XWUIInputJson/testers/TesterXWUIInputJson.html"
      }
    ]
  },
  {
    "name": "XWUIInputLocation",
    "path": "component/XWUIInputLocation",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputLocation.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputLocation\\testers\\TesterXWUIInputLocation.html",
        "relativePath": "component/XWUIInputLocation/testers/TesterXWUIInputLocation.html"
      }
    ]
  },
  {
    "name": "XWUIInputNumber",
    "path": "component/XWUIInputNumber",
    "hasTesters": true,
    "testers": [
      {
        "name": "TesterXWINumberInput",
        "filename": "TesterXWINumberInput.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputNumber\\testers\\TesterXWINumberInput.html",
        "relativePath": "component/XWUIInputNumber/testers/TesterXWINumberInput.html"
      },
      {
        "name": "Default",
        "filename": "TesterXWUIInputNumber.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputNumber\\testers\\TesterXWUIInputNumber.html",
        "relativePath": "component/XWUIInputNumber/testers/TesterXWUIInputNumber.html"
      }
    ]
  },
  {
    "name": "XWUIInputOTP",
    "path": "component/XWUIInputOTP",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputOTP.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputOTP\\testers\\TesterXWUIInputOTP.html",
        "relativePath": "component/XWUIInputOTP/testers/TesterXWUIInputOTP.html"
      }
    ]
  },
  {
    "name": "XWUIInputPassword",
    "path": "component/XWUIInputPassword",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIInputPassword.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIInputPassword\\testers\\TesterXWUIInputPassword.html",
        "relativePath": "component/XWUIInputPassword/testers/TesterXWUIInputPassword.html"
      }
    ]
  },
  {
    "name": "XWUIInputPicker",
    "path": "component/XWUIInputPicker",
    "hasTesters": false,
    "testers": []
  },
  {
    "name": "XWUIItem",
    "path": "component/XWUIItem",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIItem.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIItem\\testers\\TesterXWUIItem.html",
        "relativePath": "component/XWUIItem/testers/TesterXWUIItem.html"
      },
      {
        "name": "Email",
        "filename": "TesterXWUIItemEmail.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIItem\\testers\\TesterXWUIItemEmail.html",
        "relativePath": "component/XWUIItem/testers/TesterXWUIItemEmail.html"
      },
      {
        "name": "Sandbox",
        "filename": "TesterXWUIItemSandbox.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIItem\\testers\\TesterXWUIItemSandbox.html",
        "relativePath": "component/XWUIItem/testers/TesterXWUIItemSandbox.html"
      }
    ]
  },
  {
    "name": "XWUIItemGroup",
    "path": "component/XWUIItemGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIItemGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIItemGroup\\testers\\TesterXWUIItemGroup.html",
        "relativePath": "component/XWUIItemGroup/testers/TesterXWUIItemGroup.html"
      },
      {
        "name": "Variants",
        "filename": "TesterXWUIItemGroupVariants.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIItemGroup\\testers\\TesterXWUIItemGroupVariants.html",
        "relativePath": "component/XWUIItemGroup/testers/TesterXWUIItemGroupVariants.html"
      }
    ]
  },
  {
    "name": "XWUIJsonInput",
    "path": "component/XWUIJsonInput",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIJsonInput.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIJsonInput\\testers\\TesterXWUIJsonInput.html",
        "relativePath": "component/XWUIJsonInput/testers/TesterXWUIJsonInput.html"
      }
    ]
  },
  {
    "name": "XWUIKanbanBoard",
    "path": "super/XWUIKanbanBoard",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIKanbanBoard.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIKanbanBoard\\testers\\TesterXWUIKanbanBoard.html",
        "relativePath": "super/XWUIKanbanBoard/testers/TesterXWUIKanbanBoard.html"
      }
    ]
  },
  {
    "name": "XWUIKbd",
    "path": "component/XWUIKbd",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIKbd.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIKbd\\testers\\TesterXWUIKbd.html",
        "relativePath": "component/XWUIKbd/testers/TesterXWUIKbd.html"
      }
    ]
  },
  {
    "name": "XWUILabel",
    "path": "component/XWUILabel",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUILabel.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUILabel\\testers\\TesterXWUILabel.html",
        "relativePath": "component/XWUILabel/testers/TesterXWUILabel.html"
      }
    ]
  },
  {
    "name": "XWUIList",
    "path": "component/XWUIList",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIList.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIList\\testers\\TesterXWUIList.html",
        "relativePath": "component/XWUIList/testers/TesterXWUIList.html"
      }
    ]
  },
  {
    "name": "XWUIMap",
    "path": "component/XWUIMap",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMap.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMap\\testers\\TesterXWUIMap.html",
        "relativePath": "component/XWUIMap/testers/TesterXWUIMap.html"
      }
    ]
  },
  {
    "name": "XWUIMasonry",
    "path": "component/XWUIMasonry",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMasonry.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMasonry\\testers\\TesterXWUIMasonry.html",
        "relativePath": "component/XWUIMasonry/testers/TesterXWUIMasonry.html"
      }
    ]
  },
  {
    "name": "XWUIMediaQuery",
    "path": "component/XWUIMediaQuery",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMediaQuery.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMediaQuery\\testers\\TesterXWUIMediaQuery.html",
        "relativePath": "component/XWUIMediaQuery/testers/TesterXWUIMediaQuery.html"
      }
    ]
  },
  {
    "name": "XWUIMentions",
    "path": "component/XWUIMentions",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMentions.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMentions\\testers\\TesterXWUIMentions.html",
        "relativePath": "component/XWUIMentions/testers/TesterXWUIMentions.html"
      }
    ]
  },
  {
    "name": "XWUIMenu",
    "path": "component/XWUIMenu",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenu.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenu\\testers\\TesterXWUIMenu.html",
        "relativePath": "component/XWUIMenu/testers/TesterXWUIMenu.html"
      }
    ]
  },
  {
    "name": "XWUIMenuBar",
    "path": "component/XWUIMenuBar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuBar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuBar\\testers\\TesterXWUIMenuBar.html",
        "relativePath": "component/XWUIMenuBar/testers/TesterXWUIMenuBar.html"
      }
    ]
  },
  {
    "name": "XWUIMenuContext",
    "path": "component/XWUIMenuContext",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuContext.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuContext\\testers\\TesterXWUIMenuContext.html",
        "relativePath": "component/XWUIMenuContext/testers/TesterXWUIMenuContext.html"
      }
    ]
  },
  {
    "name": "XWUIMenuDrawer",
    "path": "component/XWUIMenuDrawer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuDrawer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuDrawer\\testers\\TesterXWUIMenuDrawer.html",
        "relativePath": "component/XWUIMenuDrawer/testers/TesterXWUIMenuDrawer.html"
      }
    ]
  },
  {
    "name": "XWUIMenuDrawerSwipeable",
    "path": "component/XWUIMenuDrawerSwipeable",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuDrawerSwipeable.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuDrawerSwipeable\\testers\\TesterXWUIMenuDrawerSwipeable.html",
        "relativePath": "component/XWUIMenuDrawerSwipeable/testers/TesterXWUIMenuDrawerSwipeable.html"
      }
    ]
  },
  {
    "name": "XWUIMenuDropdown",
    "path": "component/XWUIMenuDropdown",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuDropdown.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuDropdown\\testers\\TesterXWUIMenuDropdown.html",
        "relativePath": "component/XWUIMenuDropdown/testers/TesterXWUIMenuDropdown.html"
      }
    ]
  },
  {
    "name": "XWUIMenuNavigation",
    "path": "component/XWUIMenuNavigation",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMenuNavigation.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMenuNavigation\\testers\\TesterXWUIMenuNavigation.html",
        "relativePath": "component/XWUIMenuNavigation/testers/TesterXWUIMenuNavigation.html"
      }
    ]
  },
  {
    "name": "XWUIMessageBubble",
    "path": "component/XWUIMessageBubble",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMessageBubble.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMessageBubble\\testers\\TesterXWUIMessageBubble.html",
        "relativePath": "component/XWUIMessageBubble/testers/TesterXWUIMessageBubble.html"
      }
    ]
  },
  {
    "name": "XWUIMilestoneMarker",
    "path": "component/XWUIMilestoneMarker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMilestoneMarker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMilestoneMarker\\testers\\TesterXWUIMilestoneMarker.html",
        "relativePath": "component/XWUIMilestoneMarker/testers/TesterXWUIMilestoneMarker.html"
      }
    ]
  },
  {
    "name": "XWUIMobileStepper",
    "path": "component/XWUIMobileStepper",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMobileStepper.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMobileStepper\\testers\\TesterXWUIMobileStepper.html",
        "relativePath": "component/XWUIMobileStepper/testers/TesterXWUIMobileStepper.html"
      }
    ]
  },
  {
    "name": "XWUIMultiSelect",
    "path": "component/XWUIMultiSelect",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIMultiSelect.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIMultiSelect\\testers\\TesterXWUIMultiSelect.html",
        "relativePath": "component/XWUIMultiSelect/testers/TesterXWUIMultiSelect.html"
      }
    ]
  },
  {
    "name": "XWUINativeSelect",
    "path": "component/XWUINativeSelect",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUINativeSelect.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUINativeSelect\\testers\\TesterXWUINativeSelect.html",
        "relativePath": "component/XWUINativeSelect/testers/TesterXWUINativeSelect.html"
      }
    ]
  },
  {
    "name": "XWUINav",
    "path": "component/XWUINav",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUINav.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUINav\\testers\\TesterXWUINav.html",
        "relativePath": "component/XWUINav/testers/TesterXWUINav.html"
      }
    ]
  },
  {
    "name": "XWUINavigationRail",
    "path": "component/XWUINavigationRail",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUINavigationRail.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUINavigationRail\\testers\\TesterXWUINavigationRail.html",
        "relativePath": "component/XWUINavigationRail/testers/TesterXWUINavigationRail.html"
      }
    ]
  },
  {
    "name": "XWUIPage",
    "path": "power/XWUIPage",
    "hasTesters": true,
    "testers": [
      {
        "name": "TesterXWNote",
        "filename": "TesterXWNote.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIPage\\testers\\TesterXWNote.html",
        "relativePath": "power/XWUIPage/testers/TesterXWNote.html"
      },
      {
        "name": "Default",
        "filename": "TesterXWUIPage.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIPage\\testers\\TesterXWUIPage.html",
        "relativePath": "power/XWUIPage/testers/TesterXWUIPage.html"
      }
    ]
  },
  {
    "name": "XWUIPagination",
    "path": "component/XWUIPagination",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPagination.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPagination\\testers\\TesterXWUIPagination.html",
        "relativePath": "component/XWUIPagination/testers/TesterXWUIPagination.html"
      }
    ]
  },
  {
    "name": "XWUIPDFViewer",
    "path": "super/XWUIPDFViewer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPDFViewer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIPDFViewer\\testers\\TesterXWUIPDFViewer.html",
        "relativePath": "super/XWUIPDFViewer/testers/TesterXWUIPDFViewer.html"
      }
    ]
  },
  {
    "name": "XWUIPhotoEditor",
    "path": "super/XWUIPhotoEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPhotoEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIPhotoEditor\\testers\\TesterXWUIPhotoEditor.html",
        "relativePath": "super/XWUIPhotoEditor/testers/TesterXWUIPhotoEditor.html"
      }
    ]
  },
  {
    "name": "XWUIPicker",
    "path": "component/XWUIPicker",
    "hasTesters": false,
    "testers": []
  },
  {
    "name": "XWUIPickerColor",
    "path": "component/XWUIPickerColor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPickerColor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPickerColor\\testers\\TesterXWUIPickerColor.html",
        "relativePath": "component/XWUIPickerColor/testers/TesterXWUIPickerColor.html"
      }
    ]
  },
  {
    "name": "XWUIPickerDate",
    "path": "component/XWUIPickerDate",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPickerDate.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPickerDate\\testers\\TesterXWUIPickerDate.html",
        "relativePath": "component/XWUIPickerDate/testers/TesterXWUIPickerDate.html"
      }
    ]
  },
  {
    "name": "XWUIPickerDateRange",
    "path": "component/XWUIPickerDateRange",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPickerDateRange.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPickerDateRange\\testers\\TesterXWUIPickerDateRange.html",
        "relativePath": "component/XWUIPickerDateRange/testers/TesterXWUIPickerDateRange.html"
      }
    ]
  },
  {
    "name": "XWUIPivotTable",
    "path": "super/XWUIPivotTable",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPivotTable.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIPivotTable\\testers\\TesterXWUIPivotTable.html",
        "relativePath": "super/XWUIPivotTable/testers/TesterXWUIPivotTable.html"
      }
    ]
  },
  {
    "name": "XWUIPopconfirm",
    "path": "component/XWUIPopconfirm",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPopconfirm.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPopconfirm\\testers\\TesterXWUIPopconfirm.html",
        "relativePath": "component/XWUIPopconfirm/testers/TesterXWUIPopconfirm.html"
      }
    ]
  },
  {
    "name": "XWUIPopover",
    "path": "component/XWUIPopover",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPopover.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPopover\\testers\\TesterXWUIPopover.html",
        "relativePath": "component/XWUIPopover/testers/TesterXWUIPopover.html"
      }
    ]
  },
  {
    "name": "XWUIPortal",
    "path": "component/XWUIPortal",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPortal.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIPortal\\testers\\TesterXWUIPortal.html",
        "relativePath": "component/XWUIPortal/testers/TesterXWUIPortal.html"
      }
    ]
  },
  {
    "name": "XWUIPortfolioDashboard",
    "path": "super/XWUIPortfolioDashboard",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIPortfolioDashboard.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIPortfolioDashboard\\testers\\TesterXWUIPortfolioDashboard.html",
        "relativePath": "super/XWUIPortfolioDashboard/testers/TesterXWUIPortfolioDashboard.html"
      }
    ]
  },
  {
    "name": "XWUIProgress",
    "path": "component/XWUIProgress",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIProgress.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIProgress\\testers\\TesterXWUIProgress.html",
        "relativePath": "component/XWUIProgress/testers/TesterXWUIProgress.html"
      }
    ]
  },
  {
    "name": "XWUIProgressBySubtasks",
    "path": "component/XWUIProgressBySubtasks",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIProgressBySubtasks.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIProgressBySubtasks\\testers\\TesterXWUIProgressBySubtasks.html",
        "relativePath": "component/XWUIProgressBySubtasks/testers/TesterXWUIProgressBySubtasks.html"
      }
    ]
  },
  {
    "name": "XWUIQRCode",
    "path": "component/XWUIQRCode",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIQRCode.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIQRCode\\testers\\TesterXWUIQRCode.html",
        "relativePath": "component/XWUIQRCode/testers/TesterXWUIQRCode.html"
      }
    ]
  },
  {
    "name": "XWUIRadioGroup",
    "path": "component/XWUIRadioGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIRadioGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIRadioGroup\\testers\\TesterXWUIRadioGroup.html",
        "relativePath": "component/XWUIRadioGroup/testers/TesterXWUIRadioGroup.html"
      }
    ]
  },
  {
    "name": "XWUIRangeSlider",
    "path": "component/XWUIRangeSlider",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIRangeSlider.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIRangeSlider\\testers\\TesterXWUIRangeSlider.html",
        "relativePath": "component/XWUIRangeSlider/testers/TesterXWUIRangeSlider.html"
      }
    ]
  },
  {
    "name": "XWUIRating",
    "path": "component/XWUIRating",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIRating.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIRating\\testers\\TesterXWUIRating.html",
        "relativePath": "component/XWUIRating/testers/TesterXWUIRating.html"
      }
    ]
  },
  {
    "name": "XWUIReactionSelector",
    "path": "component/XWUIReactionSelector",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIReactionSelector.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIReactionSelector\\testers\\TesterXWUIReactionSelector.html",
        "relativePath": "component/XWUIReactionSelector/testers/TesterXWUIReactionSelector.html"
      }
    ]
  },
  {
    "name": "XWUIRecurrencePicker",
    "path": "component/XWUIRecurrencePicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIRecurrencePicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIRecurrencePicker\\testers\\TesterXWUIRecurrencePicker.html",
        "relativePath": "component/XWUIRecurrencePicker/testers/TesterXWUIRecurrencePicker.html"
      }
    ]
  },
  {
    "name": "XWUIResizable",
    "path": "component/XWUIResizable",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIResizable.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIResizable\\testers\\TesterXWUIResizable.html",
        "relativePath": "component/XWUIResizable/testers/TesterXWUIResizable.html"
      }
    ]
  },
  {
    "name": "XWUIResizablePanel",
    "path": "power/XWUIResizablePanel",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIResizablePanel.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIResizablePanel\\testers\\TesterXWUIResizablePanel.html",
        "relativePath": "power/XWUIResizablePanel/testers/TesterXWUIResizablePanel.html"
      }
    ]
  },
  {
    "name": "XWUIResourceAllocationChart",
    "path": "super/XWUIResourceAllocationChart",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIResourceAllocationChart.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIResourceAllocationChart\\testers\\TesterXWUIResourceAllocationChart.html",
        "relativePath": "super/XWUIResourceAllocationChart/testers/TesterXWUIResourceAllocationChart.html"
      }
    ]
  },
  {
    "name": "XWUIResult",
    "path": "component/XWUIResult",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIResult.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIResult\\testers\\TesterXWUIResult.html",
        "relativePath": "component/XWUIResult/testers/TesterXWUIResult.html"
      }
    ]
  },
  {
    "name": "XWUIRichTextEditor",
    "path": "power/XWUIRichTextEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIRichTextEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIRichTextEditor\\testers\\TesterXWUIRichTextEditor.html",
        "relativePath": "power/XWUIRichTextEditor/testers/TesterXWUIRichTextEditor.html"
      }
    ]
  },
  {
    "name": "XWUIScriptEditor",
    "path": "super/XWUIScriptEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIScriptEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIScriptEditor\\testers\\TesterXWUIScriptEditor.html",
        "relativePath": "super/XWUIScriptEditor/testers/TesterXWUIScriptEditor.html"
      },
      {
        "name": "Three-ways",
        "filename": "TesterXWUIScriptEditor.three-ways.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIScriptEditor\\testers\\TesterXWUIScriptEditor.three-ways.html",
        "relativePath": "super/XWUIScriptEditor/testers/TesterXWUIScriptEditor.three-ways.html"
      },
      {
        "name": "React",
        "filename": "TesterXWUIScriptEditorReact.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIScriptEditor\\testers\\TesterXWUIScriptEditorReact.html",
        "relativePath": "super/XWUIScriptEditor/testers/TesterXWUIScriptEditorReact.html"
      }
    ]
  },
  {
    "name": "XWUIScrollArea",
    "path": "component/XWUIScrollArea",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIScrollArea.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIScrollArea\\testers\\TesterXWUIScrollArea.html",
        "relativePath": "component/XWUIScrollArea/testers/TesterXWUIScrollArea.html"
      }
    ]
  },
  {
    "name": "XWUIScrollTo",
    "path": "component/XWUIScrollTo",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIScrollTo.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIScrollTo\\testers\\TesterXWUIScrollTo.html",
        "relativePath": "component/XWUIScrollTo/testers/TesterXWUIScrollTo.html"
      }
    ]
  },
  {
    "name": "XWUISectionGrouping",
    "path": "component/XWUISectionGrouping",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISectionGrouping.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISectionGrouping\\testers\\TesterXWUISectionGrouping.html",
        "relativePath": "component/XWUISectionGrouping/testers/TesterXWUISectionGrouping.html"
      }
    ]
  },
  {
    "name": "XWUISegmentedControl",
    "path": "component/XWUISegmentedControl",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISegmentedControl.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISegmentedControl\\testers\\TesterXWUISegmentedControl.html",
        "relativePath": "component/XWUISegmentedControl/testers/TesterXWUISegmentedControl.html"
      }
    ]
  },
  {
    "name": "XWUISelect",
    "path": "component/XWUISelect",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISelect.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISelect\\testers\\TesterXWUISelect.html",
        "relativePath": "component/XWUISelect/testers/TesterXWUISelect.html"
      }
    ]
  },
  {
    "name": "XWUISeparator",
    "path": "component/XWUISeparator",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISeparator.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISeparator\\testers\\TesterXWUISeparator.html",
        "relativePath": "component/XWUISeparator/testers/TesterXWUISeparator.html"
      }
    ]
  },
  {
    "name": "XWUIShortcuts",
    "path": "component/XWUIShortcuts",
    "hasTesters": false,
    "testers": []
  },
  {
    "name": "XWUISidebar",
    "path": "component/XWUISidebar",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISidebar.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISidebar\\testers\\TesterXWUISidebar.html",
        "relativePath": "component/XWUISidebar/testers/TesterXWUISidebar.html"
      }
    ]
  },
  {
    "name": "XWUISignaturePad",
    "path": "component/XWUISignaturePad",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISignaturePad.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISignaturePad\\testers\\TesterXWUISignaturePad.html",
        "relativePath": "component/XWUISignaturePad/testers/TesterXWUISignaturePad.html"
      }
    ]
  },
  {
    "name": "XWUISkeleton",
    "path": "component/XWUISkeleton",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISkeleton.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISkeleton\\testers\\TesterXWUISkeleton.html",
        "relativePath": "component/XWUISkeleton/testers/TesterXWUISkeleton.html"
      }
    ]
  },
  {
    "name": "XWUISkipLink",
    "path": "component/XWUISkipLink",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISkipLink.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISkipLink\\testers\\TesterXWUISkipLink.html",
        "relativePath": "component/XWUISkipLink/testers/TesterXWUISkipLink.html"
      }
    ]
  },
  {
    "name": "XWUISlider",
    "path": "component/XWUISlider",
    "hasTesters": true,
    "testers": [
      {
        "name": "PlayerControls",
        "filename": "TesterXWUISlider-PlayerControls.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISlider\\testers\\TesterXWUISlider-PlayerControls.html",
        "relativePath": "component/XWUISlider/testers/TesterXWUISlider-PlayerControls.html"
      },
      {
        "name": "Default",
        "filename": "TesterXWUISlider.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISlider\\testers\\TesterXWUISlider.html",
        "relativePath": "component/XWUISlider/testers/TesterXWUISlider.html"
      }
    ]
  },
  {
    "name": "XWUISortableList",
    "path": "power/XWUISortableList",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISortableList.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUISortableList\\testers\\TesterXWUISortableList.html",
        "relativePath": "power/XWUISortableList/testers/TesterXWUISortableList.html"
      }
    ]
  },
  {
    "name": "XWUISpace",
    "path": "component/XWUISpace",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISpace.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISpace\\testers\\TesterXWUISpace.html",
        "relativePath": "component/XWUISpace/testers/TesterXWUISpace.html"
      }
    ]
  },
  {
    "name": "XWUISpeedDial",
    "path": "component/XWUISpeedDial",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISpeedDial.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISpeedDial\\testers\\TesterXWUISpeedDial.html",
        "relativePath": "component/XWUISpeedDial/testers/TesterXWUISpeedDial.html"
      }
    ]
  },
  {
    "name": "XWUISpinner",
    "path": "component/XWUISpinner",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISpinner.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISpinner\\testers\\TesterXWUISpinner.html",
        "relativePath": "component/XWUISpinner/testers/TesterXWUISpinner.html"
      }
    ]
  },
  {
    "name": "XWUISplitButton",
    "path": "component/XWUISplitButton",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISplitButton.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISplitButton\\testers\\TesterXWUISplitButton.html",
        "relativePath": "component/XWUISplitButton/testers/TesterXWUISplitButton.html"
      }
    ]
  },
  {
    "name": "XWUISpoiler",
    "path": "component/XWUISpoiler",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISpoiler.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISpoiler\\testers\\TesterXWUISpoiler.html",
        "relativePath": "component/XWUISpoiler/testers/TesterXWUISpoiler.html"
      }
    ]
  },
  {
    "name": "XWUISpreadsheet",
    "path": "super/XWUISpreadsheet",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISpreadsheet.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUISpreadsheet\\testers\\TesterXWUISpreadsheet.html",
        "relativePath": "super/XWUISpreadsheet/testers/TesterXWUISpreadsheet.html"
      }
    ]
  },
  {
    "name": "XWUIStack",
    "path": "component/XWUIStack",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStack.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStack\\testers\\TesterXWUIStack.html",
        "relativePath": "component/XWUIStack/testers/TesterXWUIStack.html"
      }
    ]
  },
  {
    "name": "XWUIStatistic",
    "path": "component/XWUIStatistic",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStatistic.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStatistic\\testers\\TesterXWUIStatistic.html",
        "relativePath": "component/XWUIStatistic/testers/TesterXWUIStatistic.html"
      }
    ]
  },
  {
    "name": "XWUISteps",
    "path": "component/XWUISteps",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISteps.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISteps\\testers\\TesterXWUISteps.html",
        "relativePath": "component/XWUISteps/testers/TesterXWUISteps.html"
      }
    ]
  },
  {
    "name": "XWUIStickersOverlay",
    "path": "component/XWUIStickersOverlay",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStickersOverlay.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStickersOverlay\\testers\\TesterXWUIStickersOverlay.html",
        "relativePath": "component/XWUIStickersOverlay/testers/TesterXWUIStickersOverlay.html"
      }
    ]
  },
  {
    "name": "XWUIStyle",
    "path": "component/XWUIStyle",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStyle.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStyle\\testers\\TesterXWUIStyle.html",
        "relativePath": "component/XWUIStyle/testers/TesterXWUIStyle.html"
      }
    ]
  },
  {
    "name": "XWUIStyleSelector",
    "path": "component/XWUIStyleSelector",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStyleSelector.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStyleSelector\\testers\\TesterXWUIStyleSelector.html",
        "relativePath": "component/XWUIStyleSelector/testers/TesterXWUIStyleSelector.html"
      }
    ]
  },
  {
    "name": "XWUIStyleSwitch",
    "path": "component/XWUIStyleSwitch",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIStyleSwitch.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIStyleSwitch\\testers\\TesterXWUIStyleSwitch.html",
        "relativePath": "component/XWUIStyleSwitch/testers/TesterXWUIStyleSwitch.html"
      }
    ]
  },
  {
    "name": "XWUISubtaskExpander",
    "path": "component/XWUISubtaskExpander",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISubtaskExpander.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISubtaskExpander\\testers\\TesterXWUISubtaskExpander.html",
        "relativePath": "component/XWUISubtaskExpander/testers/TesterXWUISubtaskExpander.html"
      }
    ]
  },
  {
    "name": "XWUISwitch",
    "path": "component/XWUISwitch",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUISwitch.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUISwitch\\testers\\TesterXWUISwitch.html",
        "relativePath": "component/XWUISwitch/testers/TesterXWUISwitch.html"
      }
    ]
  },
  {
    "name": "XWUITable",
    "path": "component/XWUITable",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITable.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITable\\testers\\TesterXWUITable.html",
        "relativePath": "component/XWUITable/testers/TesterXWUITable.html"
      }
    ]
  },
  {
    "name": "XWUITabs",
    "path": "component/XWUITabs",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITabs.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITabs\\testers\\TesterXWUITabs.html",
        "relativePath": "component/XWUITabs/testers/TesterXWUITabs.html"
      }
    ]
  },
  {
    "name": "XWUITag",
    "path": "component/XWUITag",
    "hasTesters": false,
    "testers": []
  },
  {
    "name": "XWUITaskTemplateSelector",
    "path": "component/XWUITaskTemplateSelector",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITaskTemplateSelector.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITaskTemplateSelector\\testers\\TesterXWUITaskTemplateSelector.html",
        "relativePath": "component/XWUITaskTemplateSelector/testers/TesterXWUITaskTemplateSelector.html"
      }
    ]
  },
  {
    "name": "XWUITester",
    "path": "component/XWUITester",
    "hasTesters": true,
    "testers": [
      {
        "name": "LoadingSolutions",
        "filename": "TesterXWUITester-LoadingSolutions.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester-LoadingSolutions.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester-LoadingSolutions.html"
      },
      {
        "name": "Solution1",
        "filename": "TesterXWUITester-Solution1.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester-Solution1.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester-Solution1.html"
      },
      {
        "name": "Solution2",
        "filename": "TesterXWUITester-Solution2.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester-Solution2.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester-Solution2.html"
      },
      {
        "name": "Solution3",
        "filename": "TesterXWUITester-Solution3.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester-Solution3.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester-Solution3.html"
      },
      {
        "name": "Solution4",
        "filename": "TesterXWUITester-Solution4.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester-Solution4.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester-Solution4.html"
      },
      {
        "name": "Default",
        "filename": "TesterXWUITester.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITester\\testers\\TesterXWUITester.html",
        "relativePath": "component/XWUITester/testers/TesterXWUITester.html"
      }
    ]
  },
  {
    "name": "XWUITextarea",
    "path": "component/XWUITextarea",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITextarea.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITextarea\\testers\\TesterXWUITextarea.html",
        "relativePath": "component/XWUITextarea/testers/TesterXWUITextarea.html"
      }
    ]
  },
  {
    "name": "XWUITextOverlay",
    "path": "component/XWUITextOverlay",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITextOverlay.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITextOverlay\\testers\\TesterXWUITextOverlay.html",
        "relativePath": "component/XWUITextOverlay/testers/TesterXWUITextOverlay.html"
      }
    ]
  },
  {
    "name": "XWUIThread",
    "path": "component/XWUIThread",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIThread.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIThread\\testers\\TesterXWUIThread.html",
        "relativePath": "component/XWUIThread/testers/TesterXWUIThread.html"
      }
    ]
  },
  {
    "name": "XWUITimeline",
    "path": "component/XWUITimeline",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITimeline.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITimeline\\testers\\TesterXWUITimeline.html",
        "relativePath": "component/XWUITimeline/testers/TesterXWUITimeline.html"
      }
    ]
  },
  {
    "name": "XWUITimelineZoom",
    "path": "component/XWUITimelineZoom",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITimelineZoom.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITimelineZoom\\testers\\TesterXWUITimelineZoom.html",
        "relativePath": "component/XWUITimelineZoom/testers/TesterXWUITimelineZoom.html"
      }
    ]
  },
  {
    "name": "XWUITimePicker",
    "path": "component/XWUITimePicker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITimePicker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITimePicker\\testers\\TesterXWUITimePicker.html",
        "relativePath": "component/XWUITimePicker/testers/TesterXWUITimePicker.html"
      }
    ]
  },
  {
    "name": "XWUITimeTracker",
    "path": "super/XWUITimeTracker",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITimeTracker.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUITimeTracker\\testers\\TesterXWUITimeTracker.html",
        "relativePath": "super/XWUITimeTracker/testers/TesterXWUITimeTracker.html"
      }
    ]
  },
  {
    "name": "XWUITitled",
    "path": "component/XWUITitled",
    "hasTesters": false,
    "testers": []
  },
  {
    "name": "XWUIToast",
    "path": "component/XWUIToast",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIToast.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIToast\\testers\\TesterXWUIToast.html",
        "relativePath": "component/XWUIToast/testers/TesterXWUIToast.html"
      }
    ]
  },
  {
    "name": "XWUIToggleGroup",
    "path": "component/XWUIToggleGroup",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIToggleGroup.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIToggleGroup\\testers\\TesterXWUIToggleGroup.html",
        "relativePath": "component/XWUIToggleGroup/testers/TesterXWUIToggleGroup.html"
      }
    ]
  },
  {
    "name": "XWUITooltip",
    "path": "component/XWUITooltip",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITooltip.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITooltip\\testers\\TesterXWUITooltip.html",
        "relativePath": "component/XWUITooltip/testers/TesterXWUITooltip.html"
      }
    ]
  },
  {
    "name": "XWUITour",
    "path": "component/XWUITour",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITour.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITour\\testers\\TesterXWUITour.html",
        "relativePath": "component/XWUITour/testers/TesterXWUITour.html"
      }
    ]
  },
  {
    "name": "XWUITransferList",
    "path": "component/XWUITransferList",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITransferList.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITransferList\\testers\\TesterXWUITransferList.html",
        "relativePath": "component/XWUITransferList/testers/TesterXWUITransferList.html"
      }
    ]
  },
  {
    "name": "XWUITransition",
    "path": "component/XWUITransition",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITransition.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITransition\\testers\\TesterXWUITransition.html",
        "relativePath": "component/XWUITransition/testers/TesterXWUITransition.html"
      }
    ]
  },
  {
    "name": "XWUITree",
    "path": "component/XWUITree",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITree.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITree\\testers\\TesterXWUITree.html",
        "relativePath": "component/XWUITree/testers/TesterXWUITree.html"
      }
    ]
  },
  {
    "name": "XWUITreeSelect",
    "path": "component/XWUITreeSelect",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITreeSelect.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITreeSelect\\testers\\TesterXWUITreeSelect.html",
        "relativePath": "component/XWUITreeSelect/testers/TesterXWUITreeSelect.html"
      }
    ]
  },
  {
    "name": "XWUITypingIndicator",
    "path": "component/XWUITypingIndicator",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITypingIndicator.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITypingIndicator\\testers\\TesterXWUITypingIndicator.html",
        "relativePath": "component/XWUITypingIndicator/testers/TesterXWUITypingIndicator.html"
      }
    ]
  },
  {
    "name": "XWUITypography",
    "path": "component/XWUITypography",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUITypography.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUITypography\\testers\\TesterXWUITypography.html",
        "relativePath": "component/XWUITypography/testers/TesterXWUITypography.html"
      }
    ]
  },
  {
    "name": "XWUIUpload",
    "path": "component/XWUIUpload",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIUpload.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIUpload\\testers\\TesterXWUIUpload.html",
        "relativePath": "component/XWUIUpload/testers/TesterXWUIUpload.html"
      }
    ]
  },
  {
    "name": "XWUIVideoEditor",
    "path": "super/XWUIVideoEditor",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIVideoEditor.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIVideoEditor\\testers\\TesterXWUIVideoEditor.html",
        "relativePath": "super/XWUIVideoEditor/testers/TesterXWUIVideoEditor.html"
      }
    ]
  },
  {
    "name": "XWUIVideoPlayer",
    "path": "super/XWUIVideoPlayer",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIVideoPlayer.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIVideoPlayer\\testers\\TesterXWUIVideoPlayer.html",
        "relativePath": "super/XWUIVideoPlayer/testers/TesterXWUIVideoPlayer.html"
      }
    ]
  },
  {
    "name": "XWUIVideoRecorder",
    "path": "super/XWUIVideoRecorder",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIVideoRecorder.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIVideoRecorder\\testers\\TesterXWUIVideoRecorder.html",
        "relativePath": "super/XWUIVideoRecorder/testers/TesterXWUIVideoRecorder.html"
      }
    ]
  },
  {
    "name": "XWUIViewport2D",
    "path": "power/XWUIViewport2D",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIViewport2D.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIViewport2D\\testers\\TesterXWUIViewport2D.html",
        "relativePath": "power/XWUIViewport2D/testers/TesterXWUIViewport2D.html"
      }
    ]
  },
  {
    "name": "XWUIViewport3D",
    "path": "power/XWUIViewport3D",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIViewport3D.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\power\\XWUIViewport3D\\testers\\TesterXWUIViewport3D.html",
        "relativePath": "power/XWUIViewport3D/testers/TesterXWUIViewport3D.html"
      }
    ]
  },
  {
    "name": "XWUIVisuallyHidden",
    "path": "component/XWUIVisuallyHidden",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIVisuallyHidden.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIVisuallyHidden\\testers\\TesterXWUIVisuallyHidden.html",
        "relativePath": "component/XWUIVisuallyHidden/testers/TesterXWUIVisuallyHidden.html"
      }
    ]
  },
  {
    "name": "XWUIWatermark",
    "path": "component/XWUIWatermark",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIWatermark.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIWatermark\\testers\\TesterXWUIWatermark.html",
        "relativePath": "component/XWUIWatermark/testers/TesterXWUIWatermark.html"
      }
    ]
  },
  {
    "name": "XWUIWorkflow",
    "path": "super/XWUIWorkflow",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIWorkflow.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\super\\XWUIWorkflow\\testers\\TesterXWUIWorkflow.html",
        "relativePath": "super/XWUIWorkflow/testers/TesterXWUIWorkflow.html"
      }
    ]
  },
  {
    "name": "XWUIWorkloadView",
    "path": "component/XWUIWorkloadView",
    "hasTesters": true,
    "testers": [
      {
        "name": "Default",
        "filename": "TesterXWUIWorkloadView.html",
        "path": "D:\\OneDrive\\DEV\\exonware\\xwui\\src\\components\\component\\XWUIWorkloadView\\testers\\TesterXWUIWorkloadView.html",
        "relativePath": "component/XWUIWorkloadView/testers/TesterXWUIWorkloadView.html"
      }
    ]
  }
];
