// Component manifest loaded from index-data.ts (generated by tools/generate-component-index.ts)
import { components } from './index-data';

let filteredComponents = [...components];

// Render components
        function renderComponents() {
            const grid = document.getElementById('componentsGrid');
            if (!grid) return;
            
            grid.innerHTML = '';
            
            if (filteredComponents.length === 0) {
                grid.innerHTML = '<div style="grid-column: 1 / -1; text-align: center; padding: 3rem; color: #999;">No components found matching your search.</div>';
                return;
            }
            
            filteredComponents.forEach(component => {
                const card = createComponentCard(component);
                grid.appendChild(card);
            });
        }
        
        // Create component card
        function createComponentCard(component) {
            const card = document.createElement('div');
            card.className = 'component-card';
            
            const title = document.createElement('h3');
            title.innerHTML = component.name + (component.testers.length > 0
                ? '<span class="tester-count">' + component.testers.length + '</span>'
                : '');
            card.appendChild(title);
            
            const description = document.createElement('div');
            description.className = 'component-description';
            description.textContent = getComponentDescription(component.name);
            card.appendChild(description);
            
            const testersDiv = document.createElement('div');
            testersDiv.className = 'testers-list';
            
            if (component.testers.length > 0) {
                component.testers.forEach(tester => {
                    const link = document.createElement('a');
                    link.className = 'tester-link';
                    link.href = '../../' + component.path + '/testers/' + tester.filename;
                    link.target = '_blank';
                    link.textContent = tester.name === 'Default'
                        ? 'Tester'
                        : tester.name.replace(component.name, '').replace(/^[._]/, '') || 'Tester';
                    link.title = 'Open ' + component.name + ' ' + tester.name + ' tester';
                    testersDiv.appendChild(link);
                });
            } else {
                const noTesters = document.createElement('span');
                noTesters.className = 'no-testers';
                noTesters.textContent = 'No testers available';
                testersDiv.appendChild(noTesters);
            }
            
            card.appendChild(testersDiv);
            
            return card;
        }
        
        // Get component description
        function getComponentDescription(componentName) {
            const descriptions = {
                'XWUIPortal': 'Render children into a DOM node outside the component hierarchy',
                'XWUITransition': 'Animation wrapper component for enter/exit transitions',
                'XWUIVisuallyHidden': 'Hide content visually while keeping it accessible to screen readers',
                'XWUIAffix': 'Pin element to viewport when scrolling',
                'XWUIBox': 'Basic layout container with flexible styling',
                'XWUIContainer': 'Layout component that centers content horizontally and sets a maximum width',
                'XWUICenter': 'Center content horizontally and/or vertically',
                'XWUISpace': 'Add spacing between elements',
                'XWUIFlex': 'Flexbox layout component',
                'XWUIStack': 'Stack children vertically or horizontally with consistent spacing',
                'XWUIBackToTop': 'Floating button to scroll to top',
                'XWUISpeedDial': 'Floating action button with expandable menu',
                'XWUIAnchor': 'Table of contents / anchor navigation',
                'XWUIPasswordInput': 'Dedicated password input with visibility toggle',
                'XWINumberInput': 'Dedicated number input with increment/decrement controls',
                'XWUIMultiSelect': 'Multi-select dropdown',
                'XWUIAutocomplete': 'Autocomplete/combobox with search',
                'XWUIRangeSlider': 'Dual-thumb slider for range selection',
                'XWUIColorPicker': 'Color picker input',
                'XWUIDateRangePicker': 'Date range selection',
                'XWUIRichTextEditor': 'Rich text/WYSIWYG editor',
                'XWUICascader': 'Cascading dropdown selection',
                'XWUIMentions': 'Mentions input (@ mentions)',
                'XWUITreeSelect': 'Tree select dropdown',
                'XWUISegmentedControl': 'Segmented button control',
                'XWUIJsonInput': 'JSON input with validation',
                'XWUIPopconfirm': 'Popover with confirmation action',
                'XWUIHoverCard': 'Popover triggered on hover',
                'XWUIWatermark': 'Watermark overlay',
                'XWUITour': 'Step-by-step guide/tour',
                'XWUIAvatarGroup': 'Group of avatars',
                'XWUIStatistic': 'Display statistics/counts',
                'XWUIDescriptionList': 'Description list (term-value pairs)',
                'XWUISpoiler': 'Collapsible content with "show more" toggle',
                'XWUIQRCode': 'QR code display',
                'XWUIWorkflow': 'Interactive workflow visualization component with nodes and connections'
            };
            
            return descriptions[componentName] || (componentName + ' component');
        }
        
        // Setup search
        function setupSearch() {
            const searchInput = document.getElementById('searchInput');
            if (!searchInput) return;
            
            searchInput.addEventListener('input', (e) => {
                const query = e.target.value.toLowerCase().trim();
                
                if (!query) {
                    filteredComponents = [...components];
                } else {
                    filteredComponents = components.filter(comp => {
                        const nameMatch = comp.name.toLowerCase().includes(query);
                        const testerMatch = comp.testers.some(t => 
                            t.name.toLowerCase().includes(query) || 
                            t.filename.toLowerCase().includes(query)
                        );
                        const descMatch = getComponentDescription(comp.name).toLowerCase().includes(query);
                        
                        return nameMatch || testerMatch || descMatch;
                    });
                }
                
                renderComponents();
                updateStats();
            });
        }
        
        // Update statistics
        function updateStats() {
            const stats = document.getElementById('stats');
            if (!stats) return;
            
            const totalComponents = components.length;
            const componentsWithTesters = components.filter(c => c.testers.length > 0).length;
            const totalTesters = components.reduce((sum, c) => sum + c.testers.length, 0);
            const filteredCount = filteredComponents.length;
            
            stats.innerHTML =
                '<span><strong>' + filteredCount + '</strong> component' +
                (filteredCount !== 1 ? 's' : '') + ' shown</span>' +
                '<span><strong>' + totalComponents + '</strong> total components</span>' +
                '<span><strong>' + componentsWithTesters + '</strong> with testers</span>' +
                '<span><strong>' + totalTesters + '</strong> total testers</span>';
        }
        
        // Initialize
        renderComponents();
        updateStats();
        setupSearch();
